//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:2.0.50727.6400
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by wsdl, Version=2.0.50727.3038.
// 
namespace EnterpriseBugs.FakeWebservice.FakeService {
    using System.Xml.Serialization;
    using System.Web.Services;
    using System.ComponentModel;
    using System.Web.Services.Protocols;
    using System;
    using System.Diagnostics;
    using System.Data;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
    [System.Web.Services.WebServiceBindingAttribute(Name="CountryInformationServiceSoap", Namespace="http://www.ezzylearning.com/services/CountryInformationService.asmx")]
    public interface ICountryInformationServiceSoap {
        
        /// <remarks/>
        [System.Web.Services.WebMethodAttribute()]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.ezzylearning.com/services/CountryInformationService.asmx/GetServiceNam" +
            "e", RequestNamespace="http://www.ezzylearning.com/services/CountryInformationService.asmx", ResponseNamespace="http://www.ezzylearning.com/services/CountryInformationService.asmx", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        string GetServiceName();
        
        /// <remarks/>
        [System.Web.Services.WebMethodAttribute()]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.ezzylearning.com/services/CountryInformationService.asmx/GetCountries", RequestNamespace="http://www.ezzylearning.com/services/CountryInformationService.asmx", ResponseNamespace="http://www.ezzylearning.com/services/CountryInformationService.asmx", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        System.Data.DataSet GetCountries();
        
        /// <remarks/>
        [System.Web.Services.WebMethodAttribute()]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.ezzylearning.com/services/CountryInformationService.asmx/GetCountryByT" +
            "woLetterISOCode", RequestNamespace="http://www.ezzylearning.com/services/CountryInformationService.asmx", ResponseNamespace="http://www.ezzylearning.com/services/CountryInformationService.asmx", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        string GetCountryByTwoLetterISOCode(string twoLetterISOCode);
        
        /// <remarks/>
        [System.Web.Services.WebMethodAttribute()]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.ezzylearning.com/services/CountryInformationService.asmx/GetTwoLetterI" +
            "SOCodeByCountry", RequestNamespace="http://www.ezzylearning.com/services/CountryInformationService.asmx", ResponseNamespace="http://www.ezzylearning.com/services/CountryInformationService.asmx", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        string GetTwoLetterISOCodeByCountry(string countryName);
        
        /// <remarks/>
        [System.Web.Services.WebMethodAttribute()]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.ezzylearning.com/services/CountryInformationService.asmx/GetCountryByT" +
            "hreeLetterISOCode", RequestNamespace="http://www.ezzylearning.com/services/CountryInformationService.asmx", ResponseNamespace="http://www.ezzylearning.com/services/CountryInformationService.asmx", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        string GetCountryByThreeLetterISOCode(string threeLetterISOCode);
        
        /// <remarks/>
        [System.Web.Services.WebMethodAttribute()]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.ezzylearning.com/services/CountryInformationService.asmx/GetThreeLette" +
            "rISOCodeByCountry", RequestNamespace="http://www.ezzylearning.com/services/CountryInformationService.asmx", ResponseNamespace="http://www.ezzylearning.com/services/CountryInformationService.asmx", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        string GetThreeLetterISOCodeByCountry(string countryName);
        
        /// <remarks/>
        [System.Web.Services.WebMethodAttribute()]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.ezzylearning.com/services/CountryInformationService.asmx/GetCapitalByC" +
            "ountry", RequestNamespace="http://www.ezzylearning.com/services/CountryInformationService.asmx", ResponseNamespace="http://www.ezzylearning.com/services/CountryInformationService.asmx", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        string GetCapitalByCountry(string countryName);
        
        /// <remarks/>
        [System.Web.Services.WebMethodAttribute()]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.ezzylearning.com/services/CountryInformationService.asmx/GetAreaInKMBy" +
            "Country", RequestNamespace="http://www.ezzylearning.com/services/CountryInformationService.asmx", ResponseNamespace="http://www.ezzylearning.com/services/CountryInformationService.asmx", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        string GetAreaInKMByCountry(string countryName);
        
        /// <remarks/>
        [System.Web.Services.WebMethodAttribute()]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.ezzylearning.com/services/CountryInformationService.asmx/GetPopulation" +
            "ByCountry", RequestNamespace="http://www.ezzylearning.com/services/CountryInformationService.asmx", ResponseNamespace="http://www.ezzylearning.com/services/CountryInformationService.asmx", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        string GetPopulationByCountry(string countryName);
        
        /// <remarks/>
        [System.Web.Services.WebMethodAttribute()]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.ezzylearning.com/services/CountryInformationService.asmx/GetContinents" +
            "", RequestNamespace="http://www.ezzylearning.com/services/CountryInformationService.asmx", ResponseNamespace="http://www.ezzylearning.com/services/CountryInformationService.asmx", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        System.Data.DataSet GetContinents();
        
        /// <remarks/>
        [System.Web.Services.WebMethodAttribute()]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.ezzylearning.com/services/CountryInformationService.asmx/GetCountriesB" +
            "yContinent", RequestNamespace="http://www.ezzylearning.com/services/CountryInformationService.asmx", ResponseNamespace="http://www.ezzylearning.com/services/CountryInformationService.asmx", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        System.Data.DataSet GetCountriesByContinent(string continentCode);
        
        /// <remarks/>
        [System.Web.Services.WebMethodAttribute()]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.ezzylearning.com/services/CountryInformationService.asmx/GetCountryByC" +
            "urrencyCode", RequestNamespace="http://www.ezzylearning.com/services/CountryInformationService.asmx", ResponseNamespace="http://www.ezzylearning.com/services/CountryInformationService.asmx", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        string GetCountryByCurrencyCode(string currencyCode);
        
        /// <remarks/>
        [System.Web.Services.WebMethodAttribute()]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.ezzylearning.com/services/CountryInformationService.asmx/GetCurrencies" +
            "", RequestNamespace="http://www.ezzylearning.com/services/CountryInformationService.asmx", ResponseNamespace="http://www.ezzylearning.com/services/CountryInformationService.asmx", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        System.Data.DataSet GetCurrencies();
        
        /// <remarks/>
        [System.Web.Services.WebMethodAttribute()]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.ezzylearning.com/services/CountryInformationService.asmx/GetCurrencyCo" +
            "deByCountry", RequestNamespace="http://www.ezzylearning.com/services/CountryInformationService.asmx", ResponseNamespace="http://www.ezzylearning.com/services/CountryInformationService.asmx", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        string GetCurrencyCodeByCountry(string countryName);
        
        /// <remarks/>
        [System.Web.Services.WebMethodAttribute()]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.ezzylearning.com/services/CountryInformationService.asmx/GetCurrencyNa" +
            "meByCountry", RequestNamespace="http://www.ezzylearning.com/services/CountryInformationService.asmx", ResponseNamespace="http://www.ezzylearning.com/services/CountryInformationService.asmx", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        string GetCurrencyNameByCountry(string countryName);
        
        /// <remarks/>
        [System.Web.Services.WebMethodAttribute()]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.ezzylearning.com/services/CountryInformationService.asmx/GetCurrencyBy" +
            "CurrencyCode", RequestNamespace="http://www.ezzylearning.com/services/CountryInformationService.asmx", ResponseNamespace="http://www.ezzylearning.com/services/CountryInformationService.asmx", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        string GetCurrencyByCurrencyCode(string currencyCode);
    }
}
